/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated.owner'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated.manager'
import { Route as AuthenticatedGmRouteImport } from './routes/_authenticated.gm'
import { Route as AuthenticatedAuditorRouteImport } from './routes/_authenticated.auditor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated.admin.permissions'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated.admin.branches'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated.admin.activity'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGmRoute = AuthenticatedGmRouteImport.update({
  id: '/gm',
  path: '/gm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditorRoute = AuthenticatedAuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/auditor': typeof AuthenticatedAuditorRoute
  '/gm': typeof AuthenticatedGmRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/auditor': typeof AuthenticatedAuditorRoute
  '/gm': typeof AuthenticatedGmRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/auditor': typeof AuthenticatedAuditorRoute
  '/_authenticated/gm': typeof AuthenticatedGmRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/auditor'
    | '/gm'
    | '/manager'
    | '/owner'
    | '/admin/activity'
    | '/admin/branches'
    | '/admin/permissions'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/auditor'
    | '/gm'
    | '/manager'
    | '/owner'
    | '/admin/activity'
    | '/admin/branches'
    | '/admin/permissions'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/auditor'
    | '/_authenticated/gm'
    | '/_authenticated/manager'
    | '/_authenticated/owner'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gm': {
      id: '/_authenticated/gm'
      path: '/gm'
      fullPath: '/gm'
      preLoaderRoute: typeof AuthenticatedGmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditor': {
      id: '/_authenticated/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuthenticatedAuditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAuditorRoute: typeof AuthenticatedAuditorRoute
  AuthenticatedGmRoute: typeof AuthenticatedGmRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAuditorRoute: AuthenticatedAuditorRoute,
  AuthenticatedGmRoute: AuthenticatedGmRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
